#!/bin/bash

# Exit if not running Manjaro/Arch
if [[ ! -e /etc/pacman.conf ]]; then
    echo "Running post-install not required on this system..."
    echo "Exiting."
    exit
fi

# This script is for x86_64 and aarch64
ARCH="$(uname -m)"

# Get debugger working in Workbench:
if [[ "$ARCH" == "x86_64" ]]; then
    sudo pacman -S --needed yay
    gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys C52048C0C0748FEE227D47A2702353E0F7E48EDB
    yay -S --needed lib32-ncurses5-compat-libs ncurses5-compat-libs
elif [[ "$ARCH" == "aarch64" ]]; then
    sudo pacman -S --needed yay npm
    yay -S --needed openocd-git
fi

# Install particle packages
neopo install

# Fix and install particle-cli
if [[ "$ARCH" == "aarch64" ]]; then
    export GODE_DEBUG=info  # This is optional
    neopo particle # This will fail

    # Replace node executable
    NODE_BINARY="$(find $HOME/.particle/node-v*/bin/node)"
    mv "$NODE_BINARY" "${NODE_BINARY}.old"
    ln -s $(which node) "$NODE_BINARY"
fi

# Complete particle-cli install
neopo particle

# Modify udev rules file to use uucp instead of plugdev
# https://wiki.archlinux.org/index.php/Users_and_groups#Group_list
sed -i 's/plugdev/uucp/g' "$HOME/.particle/node_modules/particle-cli/assets/50-particle.rules"

# Setup non-root USB access
neopo particle configure usb
